#!/usr/bin/python3

from datetime import datetime
from appmodels import db, login_manager, app
from flask_login import UserMixin
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer


@login_manager.user_loader
def load_user(user_id):
    return User.query.filter_by(id=user_id).first()


class Association = Table(Base):
    Column('t_id', ForeignKey('Tutor.id'), primary_key=True)
    Column('l_id', ForeignKey('Languages.id'), primary_key=True)
    tutor = relationship("Tutor", back_populates="fluentTutors")
    languages = relationship("Languages", back_populates="lang")
)

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(20), unique=True, nullable=False)
    last_name = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(60), unique=True, nullable=False)
    password = db.Column(db.String(60), nullable=False)
    user_type = db.Column(db.String(6), nullable=False)
    reviews = db.relationship('Review', backref='author', lazy=True)
    requests = db.relationship('ParentRequests', backref='request_from', lazy=True)
    __mapper_args__ = {
        'polymorphic_identity':'Parent',
        'polymorphic_on':user_type
        }
     
    def get_reset_token(self, expires_sec=1800):
        s = Serializer(app.config['SECRET_KEY'], expires_sec)
        return s.dumps({'user_id': self.id}).decode('utf-8')
    
    @staticmethod
    def verify_reset_token(token):
        s = Serializer(app.config['SECRET_KEY'])
        try:
            user_id = s.loads(token)['user_id']
        except:
            return None
        return User.query.get(user_id)

    def __repr__(self):
        return f"User('{self.username}', '{self.email}')"

class Tutor(User, db.Model):
    #__tablename__ = 'tutor' 
    id = db.Column(db.Integer, db.ForeignKey('user.id'), primary_key=True)
    rate = db.Column(db.Float, nullable=False)
    summary =  db.Column(db.String(120), nullable=False)
    bio =  db.Column(db.String(500), nullable=False)
    placesofresidence = db.Column(db.String(30), nullable=False)
    image_file = db.Column(db.String(120), nullable=False, default='default.jpg')
    requested = db.relationship('ParentRequests', foreign_keys='ParentRequests.t_id', backref='request_to', lazy=True)
    last_message_read_time = db.Column(db.DateTime)
    lang = relationship("Languages", back_populates="fluentTutors")
    __mapper_args__ = {
        'polymorphic_identity':'Tutor',
    }

    def __repr__(self):
        return f"User('{self.username}', '{self.email}', '{self.image_file}')"
      
    def new_messages(self):
        last_read_time = self.last_message_read_time or datetime(1900, 1, 1)
        return ParentRequests.query.filter_by(request_to=self).filter(
            ParentRequests.date_requested > last_read_time).count()
        
class ParentRequests(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    t_id = db.Column(db.Integer, db.ForeignKey('tutor.id'), nullable=False)
    p_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    date_requested = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    status = db.Column(db.String(12))

    def __repr__(self):
        return f"User('{self.id}', '{self.t_id}', '{self.p_id}', '{self.date_requested}')"

class Languages(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    language = db.Column(db.String(20), nullable=False)
    fluentTutors = relationship("Tutor", back_populates="lang")

    def __repr__(self):
        return f"Languages('{self.id}', '{self.language}')"
